// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFEaTkqFX914lVmq_pLnwjAqStlGvt4Cs',
    appId: '1:60597820859:web:1123aca3e5338bee19389e',
    messagingSenderId: '60597820859',
    projectId: 'flutter-77485',
    authDomain: 'flutter-77485.firebaseapp.com',
    storageBucket: 'flutter-77485.appspot.com',
    measurementId: 'G-1K1B22J9LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbCljaAvgRwd_rtacTrPBkLu4uCCMcH-4',
    appId: '1:60597820859:android:c144e23027ee1c0f19389e',
    messagingSenderId: '60597820859',
    projectId: 'flutter-77485',
    storageBucket: 'flutter-77485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdARn0ngbwunX-w6QkhnVQ20Sqs-Ir8zY',
    appId: '1:60597820859:ios:2d1b49f42602d44e19389e',
    messagingSenderId: '60597820859',
    projectId: 'flutter-77485',
    storageBucket: 'flutter-77485.appspot.com',
    iosClientId: '60597820859-lkhjrb75c41nbrvedeb40koapghvcp04.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdARn0ngbwunX-w6QkhnVQ20Sqs-Ir8zY',
    appId: '1:60597820859:ios:6170b5a934ba60a519389e',
    messagingSenderId: '60597820859',
    projectId: 'flutter-77485',
    storageBucket: 'flutter-77485.appspot.com',
    iosClientId: '60597820859-v5oq6stjun63hkgfoub2h3ifh21olht0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin.RunnerTests',
  );
}
