const List searchJson = [
  {
    "id": 1,
    "img": "assets/mini_videos/1.png",
    "title": "Que es lactancia materna y su importancia",
    "duracion": 70800,
  },
  {
    "id": 2,
    "img": "assets/mini_videos/2.1.png",
    "title": "Beneficios de la lactancia materna",
    "duracion": 142800,
  },
  {
    "id": 3,
    "img": "assets/mini_videos/2.2.png",
    "title": "Beneficios para la madre",
    "duracion": 66600,
  },
  {
    "id": 4,
    "img": "assets/mini_videos/3.1.png",
    "title": "Que es el calostro, leche de transición y leche madura",
    "duracion": 271200,
  },
  {
    "id": 5,
    "img": "assets/mini_videos/3.2.png",
    "title": "Leche de transición",
    "duracion": 27000,
  },
  {
    "id": 6,
    "img": "assets/mini_videos/3.3.png",
    "title": "Leche Madura",
    "duracion": 30000,
  },
  {
    "id": 7,
    "img": "assets/mini_videos/3.4.png",
    "title": "Composición de la leche materna",
    "duracion": 132000,
  },
  {
    "id": 8,
    "img": "assets/mini_videos/4.1.png",
    "title": "Como saber que el bebe se alimento lo suficiente",
    "duracion": 153600,
  },
  {
    "id": 9,
    "img": "assets/mini_videos/4.2.png",
    "title": "Señales cuando el nino tiene hambre",
    "duracion": 77400,
  },
  {
    "id": 10,
    "img": "assets/mini_videos/5.png",
    "title": "Hitos del peso a vigilar con el pediatra",
    "duracion": 121200,
  },
  {
    "id": 11,
    "img": "assets/mini_videos/6.png",
    "title": "Higiene de manos, al ofrecer lactancia materna",
    "duracion": 67800,
  },
  {
    "id": 12,
    "img": "assets/mini_videos/7.png",
    "title": "Lactancia materna en tiempos de Covid-19",
    "duracion": 85800,
  },
  {
    "id": 13,
    "img": "assets/mini_videos/8.1.png",
    "title":
        "Que alimentación debe recibir una madre durante la lactancia materna",
    "duracion": 32400,
  },
  {
    "id": 14,
    "img": "assets/mini_videos/8.2.png",
    "title": "Cafeina! Se encuentra en el cafe, chocolates y las sodas",
    "duracion": 82200,
  },
  {
    "id": 15,
    "img": "assets/mini_videos/9.png",
    "title": "¿Puedo tomar medicamentos durante la lactancia materna?",
    "duracion": 76800,
  },
  {
    "id": 16,
    "img": "assets/mini_videos/10.png",
    "title": "Posiciones y tecnicas de lactancia materna",
    "duracion": 66000,
  },
  {
    "id": 17,
    "img": "assets/mini_videos/11.1.png",
    "title": "Como detectar signos y complicaciones en la lactancia materna",
    "duracion": 70200,
  },
  {
    "id": 18,
    "img": "assets/mini_videos/11.2.png",
    "title": "Grietas en los pezones",
    "duracion": 28200,
  },
  {
    "id": 19,
    "img": "assets/mini_videos/11.3.png",
    "title": "Mastitis, infección en las mamas",
    "duracion": 28200,
  },
  {
    "id": 20,
    "img": "assets/mini_videos/11.4.png",
    "title": "Conductos obstruidos",
    "duracion": 66600,
  },
  {
    "id": 21,
    "img": "assets/mini_videos/11.5.png",
    "title": "Congestión Mamaria",
    "duracion": 29400,
  },
  {
    "id": 22,
    "img": "assets/mini_videos/12.png",
    "title":
        "Como realizar masajes al seno antes de realizar la lactancia materna",
    "duracion": 24600,
  },
  {
    "id": 23,
    "img": "assets/mini_videos/13.1.png",
    "title": "Como inicar mi banco de leche en casa",
    "duracion": 81600,
  },
  {
    "id": 24,
    "img": "assets/mini_videos/13.2.png",
    "title": "Extracción manual de la leche",
    "duracion": 69600,
  },
  {
    "id": 25,
    "img": "assets/mini_videos/13.3.png",
    "title": "Almacenamiento y conservación",
    "duracion": 94800,
  },
  {
    "id": 26,
    "img": "assets/mini_videos/14.1.png",
    "title": "Que leyes apoyan la lactancia materna en Panamá Pt.1",
    "duracion": 204000,
  },
  {
    "id": 27,
    "img": "assets/mini_videos/14.2.png",
    "title": "Que leyes apoyan la lactancia materna en Panamá Pt.2",
    "duracion": 75600,
  },
  {
    "id": 28,
    "img": "assets/mini_videos/15.png",
    "title": "Diferencias entre la leche materna y la leche de vaca",
    "duracion": 34800,
  },
  {
    "id": 29,
    "img": "assets/mini_videos/16.png",
    "title": "Mitos de la lactancia materna",
    "duracion": 69600,
  },
];
